spring.application.name=CONTENT-SERVICE
server.port=8081

spring.datasource.url=jdbc:mysql://mysql-content:3306/content_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=inesjlasi588@gmail.com
spring.mail.password=awof cxoj auid oxcf

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true